### ISSUE TITLE
gradle error in package itself : (

### ISSUE THREAD

**Issue by mohank98** [DimitarPetrov/stegify-flutter-plugin#1]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "/Users/developer/Documents/repos/test_s/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/developer/.pub-cache/hosted/pub.dartlang.org/flutter_stegify-0.0.4/android/build.gradle' line: 58

* What went wrong:
A problem occurred evaluating project ':flutter_stegify'.
> Project with path ':steg' could not be found in project ':flutter_stegify'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: /Users/developer/Documents/repos/test_s/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by DimitarPetrov** [comment]
Hi @mohank98,
Thank you very much for pointing that out!
This problem occurs due to the underlying implementation is in Go and we ivoke this methods from Swift/Kotlin. With that said in order to import this plugin correctly you need to add the following lines to your `settings.gradle`

`include ':steg'` in the beginning and 

`project(':steg').projectDir = new File(project(':flutter_stegify').projectDir, 'steg')`
In the end of the file

Something like [this](https://github.com/DimitarPetrov/stegify-mobile/blob/6b196690fa7f1db18eba387f49bec22f9a7de847/android/settings.gradle)

And this should be sufficient to work.
Sorry again, i forgot to describe this in the plugin documentation.I will do this as soon as possible.

Regards,
Dimitar

**Comment by mohank98** [comment]
Thanks @DimitarPetrov for your quick response, that fixed my issue.
Keep up the good work 👍
